news_sites:
  eluniversal:
    url: https://www.eluniversal.com.co
    queries:
      homepage_article_links : '.general a'
      article_body: '.paragraph p'
      article_title: '.titulo.interna span'
  elespectador:
    url: https://www.elespectador.com
    queries:
      homepage_article_links : '.Layout.Layout_home a'
      article_body: ''
      article_title: ''


