news_sites:
  eluniversal:
    url: https://www.eluniversal.com.co
    queries:
      homepage_article_links = '.vertical.menu.menu-3 a'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links = ''


